@include("components.buttons.template",[
    "icon"=>"plus",
    "color"=>"success",
    "class"=>$class??null,
    "message"=>$message??null,
    "function"=>$function??null,
    "label"=>$label??null,
    "closeModal"=>false,
    ])