@include("components.buttons.template",[
    "icon"=>$icon??null,
    "color"=>$color??null,
    "class"=>$class??null,
    "message"=>$message??null,
    "function"=>$function??null,
    "label"=>$label??null,
    "closeModal"=>$modal??null
    ])